db = db.getSiblingDB("epsic");

db.getSiblingDB("admin").createUser({
  user: "root",
  pwd: "password",
  roles: [{ role: "root", db: "admin" }],
});

db.createCollection("students");

db.students.insertMany([
  {
    id: 1,
    name: "Alice",
    lastName: "Smith",
    class: "DEVA1A",
    dateOfBirth: "2002-05-10",
    specificProvisions: [],
  },
  {
    id: 2,
    name: "Bob",
    lastName: "Johnson",
    class: "DEVA2A",
    dateOfBirth: "2001-09-15",
    specificProvisions: [
      "À besoin d'un tiers temps supplémentaire pour les examens",
    ],
  },
  {
    id: 3,
    name: "Charlie",
    lastName: "Brown",
    class: "DEVA1A",
    dateOfBirth: "2003-03-20",
    specificProvisions: ["Allergique aux noix"],
  },
  {
    id: 4,
    name: "Diana",
    lastName: "Garcia",
    class: "DEVA2B",
    dateOfBirth: "2000-11-05",
    specificProvisions: ["Dyslexique"],
  },
  {
    id: 5,
    name: "Elena",
    lastName: "Martinez",
    class: "DEVA2A",
    dateOfBirth: "2002-07-30",
    specificProvisions: [
      "À besoin d'un tiers temps supplémentaire pour les examens",
    ],
  },
  {
    id: 6,
    name: "Frank",
    lastName: "Miller",
    class: "DEVA2B",
    dateOfBirth: "2001-01-12",
    specificProvisions: [],
  },
  {
    id: 7,
    name: "Grace",
    lastName: "Taylor",
    class: "DEVA1A",
    dateOfBirth: "2002-09-25",
    specificProvisions: ["Dyslexique"],
  },
  {
    id: 8,
    name: "Henry",
    lastName: "Brown",
    class: "DEVA2A",
    dateOfBirth: "2001-04-18",
    specificProvisions: [],
  },
  {
    id: 9,
    name: "Isabella",
    lastName: "Davis",
    class: "DEVA2B",
    dateOfBirth: "2003-02-14",
    specificProvisions: ["ADHD"],
  },
  {
    id: 10,
    name: "Jack",
    lastName: "Wilson",
    class: "DEVA1A",
    dateOfBirth: "2000-08-05",
    specificProvisions: [],
  },
  {
    id: 11,
    name: "Katherine",
    lastName: "Anderson",
    class: "DEVA2A",
    dateOfBirth: "2002-06-28",
    specificProvisions: [],
  },
  {
    id: 12,
    name: "Liam",
    lastName: "Clark",
    class: "DEVA1A",
    dateOfBirth: "2001-03-17",
    specificProvisions: ["Anorexique"],
  },
  {
    id: 13,
    name: "Mia",
    lastName: "White",
    class: "DEVA2B",
    dateOfBirth: "2002-10-30",
    specificProvisions: [],
  },
  {
    id: 14,
    name: "Noah",
    lastName: "Thomas",
    class: "DEVA2A",
    dateOfBirth: "2000-12-22",
    specificProvisions: ["À besoin d'aide pour lire"],
  },
  {
    id: 15,
    name: "Olivia",
    lastName: "Harris",
    dateOfBirth: "2003-01-05",
    specificProvisions: [
      "À besoin d'un tiers temps supplémentaire pour les examens",
    ],
  },
  {
    id: 16,
    name: "Patrick",
    lastName: "Lewis",
    class: "DEVA2A",
    dateOfBirth: "2001-07-14",
    specificProvisions: ["Dyslexique"],
  },
  {
    id: 17,
    name: "Quinn",
    lastName: "Murphy",
    class: "DEVA2B",
    dateOfBirth: "2002-04-09",
    specificProvisions: [],
  },
  {
    id: 18,
    name: "Rachel",
    lastName: "Parker",
    class: "DEVA1A",
    dateOfBirth: "2000-11-18",
    specificProvisions: [],
  },
  {
    id: 19,
    name: "Samuel",
    lastName: "Evans",
    class: "DEVA2A",
    dateOfBirth: "2003-08-03",
    specificProvisions: [],
  },
  {
    id: 20,
    name: "Tiffany",
    lastName: "Morris",
    class: "DEVA2B",
    dateOfBirth: "2001-12-15",
    specificProvisions: ["À des problèmes psycho-moteurs"],
  },
]);
